### PR TITLE
WIP: Dockerfile to test jupyterlab-rtc

### PR DESCRIPTION
**Pull request by EWouters**
I started to read some code and created a Dockerfile and a Makefile.

This is work in progress, I don't understand much of how to run the examples at this moment.

If there is any documentation on them I'd like to read it, or if someone helps me to get things running I can write some documentation.

Edit: I guess this file has some pointers: https://github.com/jupyterlab/rtc/blob/master/.github/workflows/nodejs.yml

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@EWouters You need `yarn` to run the todo example, then you should be able to follow [the instructions in the readme](https://github.com/jupyterlab/rtc#development). Did this work for you?

**Comment by EWouters** [comment]
> @EWouters You need `yarn` to run the todo example, then you should be able to follow [the instructions in the readme](https://github.com/jupyterlab/rtc#development). Did this work for you?

In the Dockerfile I install yarn, and in the readme I explain how to install yarn.

When I continue working on this I'll try to run the commands in the nodes.yml file in the docker container.

**Comment by saulshanabrook** [comment]
> When I continue working on this I'll try to run the commands in the nodes.yml file in the docker container.

Just FYI the commands in the `nodes.yml` file is for testing the work Vidar has been doing on the simple datastore implementation, which is independent of the todo example I have been working on.

**Comment by saulshanabrook** [comment]
Closing this due to inactivity

**Pull request closed without merging**
