### PR TITLE
Fix typo in url

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
github, won't let me revert the no-line at end of file diff.

**Comment by saulshanabrook** [comment]
Thanks for fixing this :)

No worries!

**Comment by hmaarrfk** [comment]
Are there any install instructions?

or just the development instructions?

**Comment by saulshanabrook** [comment]
Currently, not much is published publicly, and things are still very in flux, so it's just available for development.

**Comment by hmaarrfk** [comment]
thanks for the clarification

**Pull request merged**
